spring.application.name=CampusHub

spring.data.mongodb.uri=mongodb+srv://alfaiz786pathan_db_user:Alfaiz1521@cluster0.x02g8lb.mongodb.net/campushub?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=campushub

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alfaiz.pathan.mca@ghrcemn.raisoni.net
spring.mail.password=fbgxwztgqwmkzqns
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Debug (optional for development)
spring.mail.properties.mail.debug=true

jwt.secret=CampusHubSuperSecretKeyForJwtTokenGeneration123
jwt.expiration=86400000


cloudinary.cloud-name=Root
cloudinary.api-key=486715621663511
cloudinary.api-secret=xnF0eyQTMFbtdTOYNbQ1mB62MZQ
